config/routes.rb
Rails.application.routes.draw do
  resources :color_swatches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color_swatch.rb
class ColorSwatch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/color_swatches_controller.rb
class ColorSwatchesController < ApplicationController
  before_action :set_color_swatch, only: %i[ show edit update destroy ]

  # GET /color_swatches or /color_swatches.json
  def index
    @color_swatches = ColorSwatch.all
  end

  # GET /color_swatches/1 or /color_swatches/1.json
  def show
  end

  # GET /color_swatches/new
  def new
    @color_swatch = ColorSwatch.new
  end

  # GET /color_swatches/1/edit
  def edit
  end

  # POST /color_swatches or /color_swatches.json
  def create
    @color_swatch = ColorSwatch.new(color_swatch_params)

    respond_to do |format|
      if @color_swatch.save
        format.html { redirect_to color_swatch_url(@color_swatch), notice: "Color swatch was successfully created." }
        format.json { render :show, status: :created, location: @color_swatch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @color_swatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /color_swatches/1 or /color_swatches/1.json
  def update
    respond_to do |format|
      if @color_swatch.update(color_swatch_params)
        format.html { redirect_to color_swatch_url(@color_swatch), notice: "Color swatch was successfully updated." }
        format.json { render :show, status: :ok, location: @color_swatch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @color_swatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /color_swatches/1 or /color_swatches/1.json
  def destroy
    @color_swatch.destroy

    respond_to do |format|
      format.html { redirect_to color_swatches_url, notice: "Color swatch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_swatch
      @color_swatch = ColorSwatch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def color_swatch_params
      params.require(:color_swatch).permit(:idFormula, :idUser, :colorName, :colorHexa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/color_swatches_helper.rb
module ColorSwatchesHelper
end

app/views/color_swatches/_color_swatch.html.erb
<div id="<%= dom_id color_swatch %>">

  <p>
    <strong>Idformula:</strong>
    <%= color_swatch.idFormula %>
  </p>

  <p>
    <strong>Iduser:</strong>
    <%= color_swatch.idUser %>
  </p>

  <p>
    <strong>Colorname:</strong>
    <%= color_swatch.colorName %>
  </p>

  <p>
    <strong>Colorhexa:</strong>
    <%= color_swatch.colorHexa %>
  </p>

  

</div>

app/views/color_swatches/_form.html.erb
<%= form_with(model: color_swatch) do |form| %>
  <% if color_swatch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(color_swatch.errors.count, "error") %> prohibited this color_swatch from being saved:</h2>

      <ul>
        <% color_swatch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :idFormula, style: "display: block" %>
    <%= form.number_field :idFormula %>
  </div>

  <div>
    <%= form.label :idUser, style: "display: block" %>
    <%= form.number_field :idUser %>
  </div>

  <div>
    <%= form.label :colorName, style: "display: block" %>
    <%= form.text_field :colorName %>
  </div>

  <div>
    <%= form.label :colorHexa, style: "display: block" %>
    <%= form.text_field :colorHexa %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/color_swatches/edit.html.erb
<h1>Editing color swatch</h1>

<%= render "form", color_swatch: @color_swatch %>

<br>

<div>
  <%= link_to "Show this color swatch", @color_swatch %> |
  <%= link_to "Back to color swatches", color_swatches_path %>
</div>

app/views/color_swatches/index.html.erb
<p style="color: green"><%= notice %></p>

<%# <h1 >Color swatches</h1> %>

<%# <div id="color_swatches"> %>
  <%# <% @color_swatches.each do |color_swatch| %> %>
    <%# <%= render color_swatch %> %>
    <%# <p> %>
      <%# <%= link_to "Show this color swatch", color_swatch %> %>
    <%# </p> %>
  <%# <% end %> %>
<%# </div> %>

  <div class="main-content">
  <div class="bg-image">
      <img src="https://images.unsplash.com/photo-1610166970010-c2e6c3da7164?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80" alt="women with lipstick"  >
  </div>

  
  <div class="usable-content">
    <div> 
      <h1>bla bla bla</h1>
      <%= link_to "Quiero personalizar", new_color_swatch_path %>      
    </div>
  </div>
</div>

app/views/color_swatches/new.html.erb
<h1>Comencemos desde un punto de partida</h1>

<%= render "form", color_swatch: @color_swatch %>

<br>

<div>
  <%= link_to "Back to color swatches", color_swatches_path %>
</div>

app/views/color_swatches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @color_swatch %>

<div>
  <%= link_to "Edit this color swatch", edit_color_swatch_path(@color_swatch) %> |
  <%= link_to "Back to color swatches", color_swatches_path %>

  <%= button_to "Destroy this color swatch", @color_swatch, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Own Cosmetics App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "content.css" %>
    <%= stylesheet_link_tag "footer.css" %>

    
  </head>


  <header> 
    <h1 style="color:black;">This is header </h1>
  </header>

  <body>
      <%= yield %>
  </body>




  <footer>
    <div class="contact-exclamation">
    <h3>¡Síguenos en redes sociales!</h3>
    </div>


    <div class="two-column-layout">

    <div class="main-contact">
        <h3>Contacto</h3>
        <p>Creamos una cosmética con consciencia, ya que todos nuestros productos son formulados con los estándares de calidad de clean beauty. Queremos crear los mejores productos y de calidad. Contáctanos.        </p>
        <div class="email-contact">
            email hello@owncosmetics.mx
        </div>
        <div class="phone-contact">
            81 1301 0275
        </div>
    </div>

    <div class="subscribe-newsletter">
        <form id="singular-form">
            <h3>Suscríbete a nuestro newsletter</h3>
            <div class="email-input">
                <input type="text" placeholder="Tu correo electrónico" id="email">
            </div>
            <div class="email-input">
                <button type="button" class="addbut1">Suscribir</button>
            </div>
        </form>
    </div>

    </div>
  <footer>


</html>